# Generated by Django 6.0.6 on 2026-06-16 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarket', models.CharField(choices=[('carrefour', 'Carrefour'), ('naivas', 'Naivas'), ('quickmart', 'Quickmart'), ('chandarana', 'Chandarana'), ('other', 'Other')], max_length=100)),
                ('delivery_address', models.TextField()),
                ('shopping_list', models.FileField(upload_to='shopping_lists/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('shopping', 'Shopping'), ('payment', 'Awaiting Payment'), ('delivery', 'Out For Delivery'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppinRequest',
        ),
    ]
