# Generated by Django 6.0.6 on 2026-06-17 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingrequest_delete_shoppinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingrequest',
            name='shopping_list_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoppingrequest',
            name='shopping_list',
            field=models.FileField(blank=True, null=True, upload_to='shopping_lists/'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppingrequest')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_jobs', to=settings.AUTH_USER_MODEL)),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
