# Generated by Django 6.0.6 on 2026-06-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_shoppingrequest_shopping_list_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('shopping', 'Shopping'), ('payment', 'Awaiting Payment'), ('delivery', 'Out For Delivery'), ('completed', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='shopping.shoppingrequest')),
            ],
        ),
    ]
